### ISSUE TITLE
❓How to schedule a Periodic Task

### ISSUE THREAD

**Issue by kterto** [vrtdev/flutter_workmanager#4]
I've been trying to use the package, but I couldn't find out where to put the code to perform the desired Task. As I understood from the working example and from the plugin implementation, I would have to write a custom class that extends the Worker and override the doWork function, but when installing the package by pubspec I wasn't able to find out where to put it.

**Comment by timrijckaert** [comment]
Hi @kterto,  👋 

Thanks for checking out this package.  
You are actually the first to open up an issue.   

The background job you wish to execute should be written in Dart, you do not need to do any native work to make it work.
Could you describe your use case, so I can understand it better?

**Comment by kterto** [comment]
Hi, @timrijckaert, that's my use case: 
I would like to perform Firebase requests periodically to check data with the app not executing and trigger an alarm when some condition is met and wake the app.  
Thank's for the reply.

**Comment by timrijckaert** [comment]
Alright, you would want to do something like this:  

Define a top level function lets call it `callbackDispatcher` here, but you could name it whatever you want.  
This function will be called in the background.  

You need to return either `true` or `false`.  
Whether your Firebase syncing was successful or not.  

```
void callbackDispatcher() {
  Workmanager.executeTask((task) {
    switch (task) {
      case "firebaseSyncing":
        print("sync with Firebase");
        break;
    }

    // Return whether the job ran successful or not.
    return Future.value(true);
  });
}
```

You then need to initialize the plugin with this function.  
In your case you wish to have a task that runs every X time.  
Therefore you use the `Workmanager#registerPeriodicTask` method to schedule a task that will run every X time.  
You can configure the time and other constraints (please look in the README).  

```
void main() {
  Workmanager.initialize(callbackDispatcher);
  Workmanager.registerPeriodicTask("1", "firebaseSyncing");
  runApp(MyApp());
}
```

Let me know if it works.

**Comment by kterto** [comment]
Ok, I've been doing something like what you've just said, but where I define the action? Where am I supposed to write the body of the actual function firebaseSyncing that I want to run in the background?

**Comment by timrijckaert** [comment]
```
print("sync with Firebase");
```

**Comment by kterto** [comment]
Now the problem is said to be that executeTask is not implemented in the Workmanager.

**Comment by timrijckaert** [comment]
I corrected the original answer to reflect the required method for `v0.0.6` of the library.

**Comment by timrijckaert** [comment]
Does it work for you now?
Can this be closed?

**Comment by kterto** [comment]
I had a problem in the machine and I had to restart... But it's not working yet.
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 3529): Failed to handle method call

**Comment by timrijckaert** [comment]
You are most likely running the app on an iOS simulator?  
Version `v0.0.6` will only work for Android. Therefore you should wrap your calls to check if it runs on Android.

```
if (Platform.isAndroid) {
  Workmanager.initialize(callbackDispatcher);
  Workmanager.registerPeriodicTask("1", "firebaseSyncing");
}

We are currently working on implementing iOS support in an upcoming version.  

Let me know if it works.

**Comment by kterto** [comment]
Actually I'm running in my android Mobile, not in a simulator. I've wrapped the code in the if statement and still not working.

**Comment by timrijckaert** [comment]
Could you send me the code please

**Comment by kterto** [comment]
That's what I'm trying to do:

void main() async {  
  Intl.defaultLocale = 'pt_BR';
  await initializeDateFormatting("pt_BR", null);

  Provider.debugCheckInvalidValueType = null;
  
  if (Platform.isAndroid) {
    Workmanager.initialize(callbackDispatcher);
    Workmanager.registerPeriodicTask("1", "firebaseSyncing");
  }

  runApp(App());
}


void callbackDispatcher() {
  Workmanager.defaultCallbackDispatcher((task) {
    switch (task) {
      case "firebaseSyncing":
        // print("sync with Firebase");
        firebaseSync();
        break;
    }

    // Return whether the job ran successful or not.
    return Future.value(true);
  });
}

Future<bool> firebaseSync() {
  print('syncing with Firebase');

  return Future.value(true);

}

**Comment by timrijckaert** [comment]
Yes I see we have a small bug.  
Thanks for reporting this, we will fix it in the upcoming release.  
For now you should set the `isInDebugMode` flag. 

```
void main() async {
  if (Platform.isAndroid) {
    Workmanager.initialize(callbackDispatcher, isInDebugMode: true);
    Workmanager.registerPeriodicTask("1", "firebaseSyncing");
  }
  runApp(App());
}
```

**Comment by kterto** [comment]
outcome with the isInDebugMode flag:
[debugMode.txt](https://github.com/vrtdev/flutter_workmanager/files/3453596/debugMode.txt)

**Comment by timrijckaert** [comment]
> I/WM-WorkerWrapper( 6599): Worker result SUCCESS for Work [ id=a54cb75b-569b-45b5-807f-5c4346129bc0, tags={ be.tramckrijte.workmanager.EchoingWorker } ]

It worked! 
Congratz ;)

**Comment by kterto** [comment]
If I run without the isInDebugMode flag, I still get an error. Is there any way of running in debug mode and not showing the system notification?

**Comment by timrijckaert** [comment]
You could set the `isInDebugMode` to `false` that would work.  

I also just updated the plugin to version `v0.0.6+1`, it fixes the bug.
With `v0.0.6+1` you don't need to explicitly set the `isDebugMode` flag no more.  

```
Workmanager. initialize(callbackDispatcher);
```

**Comment by kterto** [comment]
(sorry to keep reopening this issue, should I use another one?)
Well, when trying to call another plugins, like the firebase_auth, in the callbackDispatcher, I've been facing a problem related to the plugins's own methodChannel... so using functions are not working. 
So far I've just succeeded printing to the console some message. I've tried using a local plugin too that I had started just to access native alarm sound and trigger it, it works alone, but in integration with Workmanager it doesn't.  
The errors are like this: 
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method FirebaseApp#appNamed on channel plugins.flutter.io/firebase_core)

**Comment by timrijckaert** [comment]
I just tested myself with a simple plugin `path_provider` and I have the same issue.
Seems there is a bug when using background tasks in combination with `plugins`.  

It's better to open up a different issue as this is totally separate bug.  
I wonder if it is similar to this [issue](https://github.com/flutter/flutter/issues/14137)

**Comment by AxesandGrinds** [comment]
Was there a solution to this? Are method calls not working in workmanager?
